### ISSUE TITLE
Chris' packaging TODO list

### ISSUE THREAD

**Issue by SpotlightKid** [osam-cologne/archlinux-proaudio#9]
# Chris' packaging TODO list

## Packages for software I maintain:

* [x] [midiomatic](https://aur.archlinux.org/packages/midiomatic) #14
* [x] [python-pyjacklib ](https://aur.archlinux.org/packages/python-pyjacklib) #21
* [x] [python-rtmidi](https://aur.archlinux.org/packages/python-rtmidi) #17
* [x] [qjackcapture](https://aur.archlinux.org/packages/qjackcapture) #22
* [x] [ykchorus](https://aur.archlinux.org/packages/ykchorus) #18

## Software where I maintain an AUR release package:

* [x] [abcm2ps](https://aur.archlinux.org/packages/abcm2ps) #44
* [x] [abcpp](https://aur.archlinux.org/packages/abcpp) #141
* [x] [a-sid](https://aur.archlinux.org/packages/a-sid) #122
* [x] [darkice](https://aur.archlinux.org/packages/darkice) #153
* [x] [die-plugins](https://aur.archlinux.org/packages/die-plugins) #118
* [x] [dxconvert](https://aur.archlinux.org/packages/dxconvert) #155
* [x] [fatfrog.lv2](https://aur.archlinux.org/packages/fatfrog.lv2) #142
* [x] [fluida.lv2](https://aur.archlinux.org/packages/fluida.lv2) #128
* [x] [fogpad](https://aur.archlinux.org/packages/fogpad) #149
* [x] [ildaeil](https://aur.archlinux.org/packages/ildaeil) #57
* [x] [jalv-select](https://aur.archlinux.org/packages/jalv-select) #39
* [x] [jkmeter](https://aur.archlinux.org/packages/jkmeter) #135
* [x] [jmeters](https://aur.archlinux.org/packages/jmeters) #136
* [x] [littlefly.lv2](https://aur.archlinux.org/packages/littlefly.lv2) #143
* [x] [mclk.lv2](https://aur.archlinux.org/packages/mclk.lv2) #15
* [x] [python-mido](https://aur.archlinux.org/packages/python-mido) #121
* [x] [python-soundfile](https://aur.archlinux.org/packages/python-soundfile) #117
* [x] [rezonateur](https://aur.archlinux.org/packages/rezonateur) #156 
* [x] [sfzlint](https://aur.archlinux.org/packages/sfzlint) #158
* [x] [stone-phaser ](https://aur.archlinux.org/packages/stone-phaser ) #31
* [x] [string-machine](https://aur.archlinux.org/packages/string-machine) #13
* [x] [triceratops-lv2](https://aur.archlinux.org/packages/triceratops-lv2) #154
* [x] [xtuner](https://aur.archlinux.org/packages/xtuner) #137

## Software where I co-maintain an AUR release package:

* [x] [linux-show-player](https://aur.archlinux.org/packages/linux-show-player) #120
* [x] [ot-simian](https://aur.archlinux.org/packages/ot-simian) #119

## Other 

* [x] [abcmidi](https://aur.archlinux.org/packages/abcmidi) #152
* [x] [klick](https://aur.archlinux.org/packages/klick-git) #11 

# Won't package

* ~~[drops](https://aur.archlinux.org/packages/drops)~~
   * has no source distribution for latest release.
   * Does not work properly when compiled against system sfizz library.
   * sfizz has too many sub-modules to make including it via Github-generated
     source archives practical.
* ~~[synthclone](https://aur.archlinux.org/packages/synthclone)~~
   * Official version only supports Qt4.
   * Fork from https://github.com/edogawa23/synthclone has no releases.
* ~~[lv2proc](https://aur.archlinux.org/packages/lv2proc)~~
   * Last release from 2014.
   * [lv2file](https://archlinux.org/packages/community/x86_64/lv2file/) can probably used instead.
* ~~[tunefish4](https://aur.archlinux.org/packages/tunefish4)~~
   * Latest version 4.2.0 does not build.
   * Can't build without VST2 headers, which are not distributed anymore.
   * [LV2 fork](https://github.com/jpcima/tunefish/tree/lv2) has no new releases.

**Comment by SpotlightKid** [comment]
All done.
